FROM python:3.8-slim

ENV PYTHONBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir -r /tmp/requirements.txt \
    && rm -rf /tmp/requirements.txt \
    && useradd -U app_user \
    && pip3 install --no-cache-dir -r /tmp/requirements.txt \
    && install -d -m 0755 app_user -g app_user /app/static

RUN mkdir /code/
WORKDIR /code/
ADD . /code/
EXPOSE 8000

USER app_user:app_user

COPY --chown=app_user:app_user . .

#RUN chmod +x docker/*.sh

#ENTRYPOING ['docker/entrypoint.sh']
#CMD ["docker/start.sh", "server"]
# https://www.caktusgroup.com/blog/2017/03/14/production-ready-dockerfile-your-python-django-app/
