# Generated by Django 3.2.15 on 2022-12-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('NS', 'Not Set'), ('ML', 'Male'), ('FM', 'Female'), ('TS', 'Transgender')], default='NS', max_length=20)),
                ('email', models.CharField(blank=True, max_length=25)),
                ('mobile', models.CharField(blank=True, max_length=45)),
                ('onboarding_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('publisher_email', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('IF', 'Infotainment'), ('EN', 'Entertainment'), ('HR', 'Horror'), ('BG', 'Biography'), ('SF', 'Scifi')], max_length=20)),
                ('isn_number', models.CharField(blank=True, max_length=200)),
                ('publication_date', models.DateField()),
                ('authors', models.ManyToManyField(to='bookstore.Authors')),
                ('publisher_partners', models.ManyToManyField(blank=True, to='bookstore.Publishers')),
            ],
        ),
    ]
