# Generated by Django 3.2.15 on 2022-12-27 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_title', models.CharField(default='Unknown', max_length=100)),
                ('place_category', models.CharField(choices=[('ML', 'Mall'), ('PK', 'Park'), ('MU', 'Museum'), ('WP', 'Water Park'), ('GO', 'Government Office'), ('AH', 'Ancient Heritage'), ('OT', 'Others')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('is_public_allowed', models.BooleanField(default=False)),
                ('attributes', models.ManyToManyField(to='touristmap.PlaceAttributes')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.state')),
            ],
        ),
    ]
