# Generated by Django 3.2.15 on 2022-12-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
        ('touristmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAgents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=150)),
                ('transportation_medium', models.CharField(choices=[('TR', 'Train'), ('BS', 'Bus'), ('AB', 'Airbus'), ('YC', 'Yatch')], max_length=20)),
                ('is_international_agent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('city_coverage', models.ManyToManyField(to='world.City')),
                ('country_coverage', models.ManyToManyField(to='world.Country')),
            ],
        ),
    ]
